### ISSUE TITLE
GridLayout Dependency Issue

### ISSUE THREAD

**Issue by lawloretienne** [jacobmoncur/QuiltViewLibrary#25]
How do you set up the gridlayout_v7 dependency in Android Studio in a gradle project?

**Comment by lawloretienne** [comment]
I get this error when adding a QuiltView to my project 

`android.view.InflateException: Binary XML file line #64: Error inflating class com.biggu.shopsavvy.view.QuiltView
            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)`
